import Head from 'next/head'
import Image from 'next/image'
import Login from '../components/Login'
import UserDashboard from '../components/UserDashboard'
import { useAuth } from '../context/AuthContext'


export default function Home() {

  const {currentUser} = useAuth()
  //console.log(currentUser)
 
  return (
    < >
      <Head>
        <title>WriTe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      
      {!currentUser && <Login />}
      {currentUser && <UserDashboard/>}
       </>
  )
}
